### PR TITLE
Proofing fixes

### PR DESCRIPTION
**Pull request by robinwhittleton**
The biggest is reverting the caps changes, but there are a few other things I’ve tidied up here:

- Some various transcription mistakes
- Diary entry semantics
- Removed non-binomial species italicisation

@thewchan: ccing you for reference for your future productions, but please don’t feel bad about this. Some of this I should have caught in review anyway, and our books go through a process of continual review anyway as our guidelines evolve 🙂

### CODE REVIEW

**Comment by thewchan** [comment]
Wow! Thanks so much! I don't have to do anything on my end right? If I accept the pull request and merge it'll just merge the corrections on my repo, not the one on StardardEbooks?

**Comment by robinwhittleton** [comment]
No, nothing for you to do Matt, this is a PR to Alex to review; once it’s approved then it’ll republish a new edition of the book.

You’re welcome to delete your original repo (I do when I’m producing a book) then form the SE version if you want to make changes in future.

**Comment by acabal** [comment]
Looks very good, thanks for catching these.

A few note:

- Convolvulus should be lowercased, as it's also the common plant name

- Palmacites should also be lowercased as it's a kind of fossilized palm, not a taxon

- Mesopitheca, Leptotheria, and the rest in that paragraph should retain taxon italics as they are genus names.

Great work, thanks Robin!

**Comment by thewchan** [comment]
Got it. Thanks again! I hope I'll get better at this in the future!

**Comment by robinwhittleton** [comment]
Thanks Alex, amended those (and a few others I found in the process).

**Comment by acabal** [comment]
Thanks!

**Pull request merged**
